### GET all users
GET http://localhost:3000/users

### Create user
POST http://localhost:3000/users

### GET user by ID
GET http://localhost:3000/users/87

### DELETE user by ID
DELETE http://localhost:3000/users/87